name: Build Geode Mod

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Kita set manual path SDK-nya di sini, gak usah pake setup-geode
      - name: Build Mod
        uses: geode-sdk/build-geode-mod@main
        with:
          target: Android64
        env:
          GEODE_SDK: /home/runner/.local/share/Geode/sdk
